# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\devices\Target_Stage\singleAxisControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 416)
        self.RefreshGroupsButton = QtWidgets.QPushButton(Form)
        self.RefreshGroupsButton.setGeometry(QtCore.QRect(10, 70, 101, 41))
        self.RefreshGroupsButton.setObjectName("RefreshGroupsButton")
        self.GroupNameLabel = QtWidgets.QLabel(Form)
        self.GroupNameLabel.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.GroupNameLabel.setObjectName("GroupNameLabel")
        self.PositionLabel = QtWidgets.QLabel(Form)
        self.PositionLabel.setGeometry(QtCore.QRect(10, 280, 91, 21))
        self.PositionLabel.setObjectName("PositionLabel")
        self.MinTravelLabel = QtWidgets.QLabel(Form)
        self.MinTravelLabel.setGeometry(QtCore.QRect(10, 330, 141, 21))
        self.MinTravelLabel.setObjectName("MinTravelLabel")
        self.MaxTravelLabel = QtWidgets.QLabel(Form)
        self.MaxTravelLabel.setGeometry(QtCore.QRect(10, 360, 141, 21))
        self.MaxTravelLabel.setObjectName("MaxTravelLabel")
        self.X_LeftRelativeMoveButton = QtWidgets.QPushButton(Form)
        self.X_LeftRelativeMoveButton.setGeometry(QtCore.QRect(10, 150, 71, 31))
        self.X_LeftRelativeMoveButton.setObjectName("X_LeftRelativeMoveButton")
        self.XaxisLabel = QtWidgets.QLabel(Form)
        self.XaxisLabel.setGeometry(QtCore.QRect(40, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.XaxisLabel.setFont(font)
        self.XaxisLabel.setObjectName("XaxisLabel")
        self.RelativeMoveLabel = QtWidgets.QLabel(Form)
        self.RelativeMoveLabel.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.RelativeMoveLabel.setObjectName("RelativeMoveLabel")
        self.AbsoluteMoveLabel = QtWidgets.QLabel(Form)
        self.AbsoluteMoveLabel.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.AbsoluteMoveLabel.setObjectName("AbsoluteMoveLabel")
        self.X_AbsoluteMoveButton = QtWidgets.QPushButton(Form)
        self.X_AbsoluteMoveButton.setGeometry(QtCore.QRect(110, 230, 71, 31))
        self.X_AbsoluteMoveButton.setObjectName("X_AbsoluteMoveButton")
        self.MinTravelValue = QtWidgets.QLineEdit(Form)
        self.MinTravelValue.setGeometry(QtCore.QRect(150, 330, 71, 22))
        self.MinTravelValue.setObjectName("MinTravelValue")
        self.AbsoluteMoveValue = QtWidgets.QDoubleSpinBox(Form)
        self.AbsoluteMoveValue.setGeometry(QtCore.QRect(10, 230, 71, 31))
        self.AbsoluteMoveValue.setObjectName("AbsoluteMoveValue")
        self.X_RightRelativeMoveButton = QtWidgets.QPushButton(Form)
        self.X_RightRelativeMoveButton.setGeometry(QtCore.QRect(170, 150, 71, 31))
        self.X_RightRelativeMoveButton.setObjectName("X_RightRelativeMoveButton")
        self.RelativeMoveValue = QtWidgets.QDoubleSpinBox(Form)
        self.RelativeMoveValue.setGeometry(QtCore.QRect(90, 150, 71, 31))
        self.RelativeMoveValue.setDecimals(3)
        self.RelativeMoveValue.setProperty("value", 0.0)
        self.RelativeMoveValue.setObjectName("RelativeMoveValue")
        self.X_GroupNames = QtWidgets.QComboBox(Form)
        self.X_GroupNames.setGeometry(QtCore.QRect(120, 80, 121, 21))
        self.X_GroupNames.setObjectName("X_GroupNames")
        self.PositionValue = QtWidgets.QLCDNumber(Form)
        self.PositionValue.setGeometry(QtCore.QRect(110, 270, 61, 41))
        self.PositionValue.setSmallDecimalPoint(False)
        self.PositionValue.setProperty("value", 0.0)
        self.PositionValue.setObjectName("PositionValue")
        self.MaxTravelValue = QtWidgets.QLineEdit(Form)
        self.MaxTravelValue.setGeometry(QtCore.QRect(150, 360, 71, 22))
        self.MaxTravelValue.setObjectName("MaxTravelValue")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RefreshGroupsButton.setText(_translate("Form", "Refresh Groups"))
        self.GroupNameLabel.setText(_translate("Form", "Group Name:"))
        self.PositionLabel.setText(_translate("Form", "Position (mm):"))
        self.MinTravelLabel.setText(_translate("Form", "Minimum Travel (mm):"))
        self.MaxTravelLabel.setText(_translate("Form", "Maximum Travel (mm):"))
        self.X_LeftRelativeMoveButton.setText(_translate("Form", "Left"))
        self.XaxisLabel.setText(_translate("Form", "X-Axis"))
        self.RelativeMoveLabel.setText(_translate("Form", "Relative Move (mm)"))
        self.AbsoluteMoveLabel.setText(_translate("Form", "Absolute Move (mm)"))
        self.X_AbsoluteMoveButton.setText(_translate("Form", "Move"))
        self.X_RightRelativeMoveButton.setText(_translate("Form", "Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
