# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\devices\NewportPicomotor\multiMirror_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1346, 897)
        MainWindow.setStyleSheet("font-size: 14pt; \n"
"font-weight: bold")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connection_layout = QtWidgets.QHBoxLayout()
        self.connection_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.connection_layout.setObjectName("connection_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_layout.addItem(spacerItem)
        self.LEDindicator = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDindicator.sizePolicy().hasHeightForWidth())
        self.LEDindicator.setSizePolicy(sizePolicy)
        self.LEDindicator.setStyleSheet("background-color: red;border-radius: 10px;min-width: 20px;min-height: 20px")
        self.LEDindicator.setText("")
        self.LEDindicator.setObjectName("LEDindicator")
        self.connection_layout.addWidget(self.LEDindicator)
        self.connectionStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.connectionStatusLabel.setStyleSheet("\"font-size: 14pt; font-weight: bold\"")
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.connection_layout.addWidget(self.connectionStatusLabel)
        self.safety_button = QtWidgets.QPushButton(self.centralwidget)
        self.safety_button.setStyleSheet("background-color: blue; \n"
"color: white;\n"
"border-radius: 15px;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"padding: 10px;\n"
"border: 2px solid #333333;")
        self.safety_button.setObjectName("safety_button")
        self.connection_layout.addWidget(self.safety_button)
        self.safety_status_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.safety_status_label.sizePolicy().hasHeightForWidth())
        self.safety_status_label.setSizePolicy(sizePolicy)
        self.safety_status_label.setStyleSheet("background-color: qlineargradient(\n"
"                        spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                        stop:0 #FF6666, stop:1 #CC0000);\n"
"                    color: white;\n"
"                    border-radius: 10px;\n"
"                    font-style: italic;                           \n"
"                    font-size: 12pt;\n"
"                    font-weight: bold;\n"
"                    padding: 5px;\n"
"                    border: 2px solid #AA0000;\n"
"                    text-align: center")
        self.safety_status_label.setObjectName("safety_status_label")
        self.connection_layout.addWidget(self.safety_status_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_layout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.connection_layout)
        self.mirrorLayout = QtWidgets.QHBoxLayout()
        self.mirrorLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mirrorLayout.setObjectName("mirrorLayout")
        self.verticalLayout_3.addLayout(self.mirrorLayout)
        self.irisWidget = IrisGUIWidget(self.centralwidget)
        self.irisWidget.setObjectName("irisWidget")
        self.verticalLayout_3.addWidget(self.irisWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout_3.setStretch(2, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "Connected Controllers: 0"))
        self.safety_button.setText(_translate("MainWindow", "Disable Safety"))
        self.safety_status_label.setText(_translate("MainWindow", "High Power Mode"))
from devices.Iris.irisgui import IrisGUIWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
