# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XPSControlPanelMultiAxisTest_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(478, 472)
        self.XPSstatus = QtWidgets.QGroupBox(Form)
        self.XPSstatus.setGeometry(QtCore.QRect(10, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.XPSstatus.setFont(font)
        self.XPSstatus.setObjectName("XPSstatus")
        self.XPSstatusLabel = QtWidgets.QLabel(self.XPSstatus)
        self.XPSstatusLabel.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.XPSstatusLabel.setObjectName("XPSstatusLabel")
        self.InitializeXPS = QtWidgets.QPushButton(Form)
        self.InitializeXPS.setGeometry(QtCore.QRect(30, 110, 93, 41))
        self.InitializeXPS.setObjectName("InitializeXPS")
        self.HomeXPS = QtWidgets.QPushButton(Form)
        self.HomeXPS.setGeometry(QtCore.QRect(30, 180, 93, 41))
        self.HomeXPS.setObjectName("HomeXPS")
        self.EnableDisableXPS = QtWidgets.QPushButton(Form)
        self.EnableDisableXPS.setGeometry(QtCore.QRect(30, 250, 93, 41))
        self.EnableDisableXPS.setObjectName("EnableDisableXPS")
        self.KillAll = QtWidgets.QPushButton(Form)
        self.KillAll.setGeometry(QtCore.QRect(30, 320, 93, 41))
        self.KillAll.setObjectName("KillAll")
        self.widget = singleAxisControl(Form)
        self.widget.setGeometry(QtCore.QRect(169, 30, 261, 411))
        self.widget.setObjectName("widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.XPSstatus.setTitle(_translate("Form", "XPS Status"))
        self.XPSstatusLabel.setText(_translate("Form", "Not Initialized"))
        self.InitializeXPS.setText(_translate("Form", "Initialize XPS"))
        self.HomeXPS.setText(_translate("Form", "Home XPS"))
        self.EnableDisableXPS.setText(_translate("Form", "Enable XPS"))
        self.KillAll.setText(_translate("Form", "Kill All"))
from singleAxisControl import singleAxisControl


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
